FROM maven:3.9.6-eclipse-temurin-25 AS build
WORKDIR /app

COPY ../pom.xml .
RUN mvn clean package -DskipTests

FROM eclipse-temurin:25-jdk
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

COPY --from=build /app/target/*.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]